version: '3.7'
volumes:
  dbdata:

services:
  api:
    build: ./api
    environment:
      db_connection_str: root:root@(localhost:33061)/biologysvelte?charset=utf8&parseTime=True&loc=Local
      GOOGLE_ID: id
      GOOGLE_SECRET: secret
      # jwt_secret: origro3rnon4g04j30gjwoifnonNNININInfifn202009)*(#*@(*#(hfunjfnkdsnkfs)))
    depends_on:
      - mysql
    ports:
      - 8080:8080
  client:
    build: ./client
    depends_on:
      - mysql
    ports:
      - 3000:3000
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=biologysvelte
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - '33061:3306'
